In [95]:
import pandas as pd
from operator import itemgetter
import networkx as nx

In [96]:
data = pd.read_csv('pre_survey.csv')

In [97]:
nodes_df = data[['NetID','Name']]
nodes_df = nodes_df.rename(columns={'Name':'Label'})

In [98]:
nodes_df.to_csv('nodes.csv', index=False)

In [99]:
working = data.iloc[:,5:]
working = working.iloc[:,working.columns!='Last modified time']
working = working.set_index('Name')

In [100]:
test = working.stack().rename_axis(['Source','Target']).reset_index()

In [101]:
test

,Source,Target,0
0,Nikhil Chinchalkar,Nikhil Chinchalkar,I am this person
1,Nikhil Chinchalkar,Jason Wang,I speak with them at least once a week
2,Nikhil Chinchalkar,Rithya Sriram,I speak with them at least once a week
3,Nikhil Chinchalkar,Carina Lau,I speak with them at least once a week
4,Nikhil Chinchalkar,Jenny Williams,I speak with them at least once a week
...,...,...,...
1881,Stella Ma,Manya Pradeep Narayan,I've never seen/heard of this person before
1882,Stella Ma,Adam Azevedo,I've never seen/heard of this person before
1883,Stella Ma,Isha Nagireddy,I've never seen/heard of this person before
1884,Stella Ma,Natan Kramskiy,I've never seen/heard of this person before
1885,Stella Ma,Wonjin Eum,I've never seen/heard of this person before

In [ ]:
test = test.rename(columns={0:'Weight'})
test

,Source,Target,Weight
0,Nikhil Chinchalkar,Nikhil Chinchalkar,I am this person
1,Nikhil Chinchalkar,Jason Wang,I speak with them at least once a week
2,Nikhil Chinchalkar,Rithya Sriram,I speak with them at least once a week
3,Nikhil Chinchalkar,Carina Lau,I speak with them at least once a week
4,Nikhil Chinchalkar,Jenny Williams,I speak with them at least once a week
...,...,...,...
1881,Stella Ma,Manya Pradeep Narayan,I've never seen/heard of this person before
1882,Stella Ma,Adam Azevedo,I've never seen/heard of this person before
1883,Stella Ma,Isha Nagireddy,I've never seen/heard of this person before
1884,Stella Ma,Natan Kramskiy,I've never seen/heard of this person before
1885,Stella Ma,Wonjin Eum,I've never seen/heard of this person before

In [103]:
test['Weight'].unique()

array(['I am this person', 'I speak with them at least once a week',
       "I've spoken to them more than once before",
       'I recognize their face/name', "I've spoken to them once before",
       "I've never seen/heard of this person before",
       'I speak with them everyday'], dtype=object)

In [ ]:
weights_map = {'I am this person':0,
               'I speak with them everyday':6,
               'I speak with them at least once a week':5,
               "I've spoken to them more than once before":4,
               "I've spoken to them once before":3,
               'I recognize their face/name':2,
               "I've never seen/heard of this person before":1}

In [105]:
test['Weight'] = test['Weight'].map(lambda x: weights_map[x])

In [106]:
test

                  Source                 Target  Weight
0     Nikhil Chinchalkar     Nikhil Chinchalkar       0
1     Nikhil Chinchalkar             Jason Wang       5
2     Nikhil Chinchalkar          Rithya Sriram       5
3     Nikhil Chinchalkar             Carina Lau       5
4     Nikhil Chinchalkar         Jenny Williams       5
...                  ...                    ...     ...
1881           Stella Ma  Manya Pradeep Narayan       1
1882           Stella Ma           Adam Azevedo       1
1883           Stella Ma         Isha Nagireddy       1
1884           Stella Ma         Natan Kramskiy       1
1885           Stella Ma             Wonjin Eum       1

[1886 rows x 3 columns]

In [107]:
test.to_csv('edges.csv', index=False)